### ISSUE TITLE
I think making a small change in the code at the docs would be enough:

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/website#263]
I think making a small change in the code at the docs would be enough:

```
const fieldArrayName = 'test';

const { fields, append, prepend, remove } = useFieldArray({
    control,
    name: fieldArrayName
  });

...
<input name={`${fieldArrayName}[${index}].name`} defaultValue={item.name} ref={register()} />
...
```

_Originally posted by @caiorios in https://github.com/react-hook-form/react-hook-form/issues/1450#issuecomment-628716215_

**Comment by muhadel** [comment]
an error occurs when input is controlled input.
