### ISSUE TITLE
Add link to "Edit this page on GitHub"

### ISSUE THREAD

**Issue by dandv** [react-hook-form/website#269]
Would make it much easier for people to contribute doc changes :)

**Comment by pmaier983** [comment]
I'll take a look into this. May also copy-pasta with changes the CONTRIBUTING.md from react-hook-form.

**Comment by pmaier983** [comment]
[This](https://github.com/react-hook-form/website/pull/292) merged PR solves this issue I believe.

**Comment by dandv** [comment]
@pmaier983: that footer links points to the repo, but we can do better: have a much more easily visible link that points to the specific file in the repo that corresponds to the page the user sees. Right now, the user still has to hunt in the repo for the corresponding file.

See how https://mongoosejs.com/docs/schematypes.html implemented [my suggestion](https://github.com/Automattic/mongoose/issues/9058) for example.

**Comment by pmaier983** [comment]
This looks awesome. Will take a look and some notes, then see how I can implement in RHF.

**Comment by bluebill1049** [comment]
@pmaier983 I will be working on the design for this after v6 released.
