### ISSUE TITLE
Form doesn't revalidate when validationContext is updated

### ISSUE THREAD

**Issue by demianalonso** [react-hook-form/website#295]
Hi, I am running into an issue that I think it doesn't match with the documentation.

I am trying to test this scenario:
1. There is a form with a single textfield and a button
2. The submit button emulates a request to a server, and returns an error
3. Change the validationContext with this information, so the validationResolver marks the field with the error

It seems that changing the validationContext doesn't re execute the validations, so the form stays as if nothing happened. No other thing but the validationContext is changed, as the user has already done its part. Shouldn't the validations get reexecuted when the validationContext changes? How can a server side error be hooked to the formed otherwise?

Here is a sandbox to reproduce it: https://codesandbox.io/s/react-hook-form-validationresolver-1j073?file=/src/App.js

Please let me know if I need to provide any other information.
Thanks!

**Comment by bluebill1049** [comment]
> Shouldn't the validations get reexecuted when the validationContext changes

what do you mean? resolver is pretty simple, it returns `values` or `errors`. after submit then it should trigger an re-render on what you have returned.

**Comment by demianalonso** [comment]
That is the thing that doesn't seem to be working. If you see the example I paste there, the component gets re renderer but react-hook-form is not executing the resolver.
Consider that this happens *after* the submit event.

The sequence is the following:
1) The user hits the submit button
2) The `onSubmit` gets executed successfully until completion
3) Some state changes as a result of this `onSubmit` (in the example a state variable in the component is updated)
4) The component gets re rendered and changes the `validationContext`
5) I would expect react-hook-form to run the `validationResolver` right away on that render but it is not.

I hope I am explaining myself properly but let me know if there is something I need to explain better

**Comment by bluebill1049** [comment]
> 4. The component gets re rendered and changes the validationContext
> 5. I would expect react-hook-form to run the validationResolver right away on that render but it is not.

`resolver` only run during submit and during validation (which is depend on your `mode`). it doesn't run on each re-render.

**Comment by demianalonso** [comment]
That was my concern, shouldn't `resolver` be re executed if the `validationContext` change?
How would you tie an error coming from the server? For example, you try to register a user whose email already exist. In this case you need to execute the submit, the request and *then* you would have the information to present to the user that the user needs to change the form.

In this type of scenarios the user doesn't need to do anything as everything happens behind the scenes. The error data will appear after the submit is done, be it in a component state (like in the example) or it might be in a redux store/recoil atom, or a Context.

How can that information be tied to the react-hook-form `resolver` in those cases if not after a re render with no change in the submit/input changes/input blur?

**Comment by bluebill1049** [comment]
> That was my concern, shouldn't `resolver` be re executed if the `validationContext` change?
> How would you tie an error coming from the server? For example, you try to register a user whose email already exist. In this case you need to execute the submit, the request and _then_ you would have the information to present to the user that the user needs to change the form.
> 
> In this type of scenarios the user doesn't need to do anything as everything happens behind the scenes. The error data will appear after the submit is done, be it in a component state (like in the example) or it might be in a redux store/recoil atom, or a Context.
> 
> How can that information be tied to the react-hook-form `resolver` in those cases if not after a re render with no change in the submit/input changes/input blur?

I am lost here, why would validationConext have to re-run resolver? it's just a context object. It's not a prop where you would hit into a `useEffect`.

if a user hits submit, the form should be disabled and when the errors come to display to the user. as the user corrects the input, resolver kick in again to check whether it's valid. it's as simple as that, obviously, you can make it more complicated and involved with state management lib, but that's your implementation level.

**Comment by demianalonso** [comment]
I would expect that if the validation context is different, then the validations may fail now, so it would trigger a re render.

> and when the errors come to display to the user.
This is my point, when the error comes from the server, I would need the validation to get re executed so the field can get its error associated.

Were you able to see the example I provided? There it is clear that between the call to `setSubmitStatus` and the user changing anything, the field should give some feedback to the user. So if I would need to display the error the same way the validations error are displayed, do I need to work it around react-hook-form?

**Comment by bluebill1049** [comment]
> I would expect that if the validation context is different, then the validations may fail now, so it would trigger a re render.

That's when you should use `triggerValidation`.

**Comment by demianalonso** [comment]
Ok, I would have expected for that to be handled automatically, since there is a distinction between `validationResolver` and `validationContext` (otherwise I would assume that there is not much difference in just having a `validationResolver` which is not memoized and can be changed by the caller of `useForm`).
It is the same issue I have with `formik` right now which doesn't re execute the validations when the context changes.

But that is life, we'll probably just need drop `formik` to write our own hehe

Thanks and sorry for the questions
